name: Automatic build/deploy
on:
  push:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:
env:
  destination: public
permissions:
  contents: write
jobs:
  github-pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build
    - name: Deploy to Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token:   ${{ secrets.GITHUB_TOKEN }}
        publish_dir:    ./${{ env.destination }}
        publish_branch: ${{ env.destination }}
        commit_message: ${{ github.event.head_commit.message }}
