name: Automatic build/deploy
on:
  push:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:
permissions:
  contents: write
  id-token: write
  pages:    write
jobs:
  github-pages:
    name:    GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Pages
      id:   pages
      uses: actions/configure-pages@v3
    - name: Install dependencies and build
      run: |
        npm ci
        npm run build
    - name: Upload output
      uses: actions/upload-pages-artifact@v1
    - name: Deploy Pages
      uses: actions/deploy-pages@v2
